---
- name: Converge
  hosts: all
  roles:
    - role: nmusatti.source_gnucobol
      vars:
        gnucobol_release: 2.2
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: source-gnucobol
      vars:
        gnucobol_release: 3.0
        gnucobol_force: true
